# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          npm install --force
          npm run build
          
      - name: 3GPP Specs Compile
        run: |
          npm install -g redoc-cli
          redoc-cli bundle -o 3gpp.md 3GPP_OpenAPISpec.yaml

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
      
      - name: Copy 3gpp
        uses: andstor/copycat-action@v3
        with:
          src_path: 3gpp.md
          dst_branch: gh-pages
          dst_owner: action
          dst_repo_name: tcs-apis
